name: Build and Push Docker Image to Portainer (CI/CD)

on:
  push:
    branches:
      - feature/portainercicd  # Replace with your working branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t jdeantech/portfolio:latest .

      - name: Push Docker image
        run: docker push jdeantech/portfolio:latest
